name: 🚀 CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop, feature/*, fix/* ]

# Grant GITHUB_TOKEN the permissions required by semantic-release
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # 🧪 Quality Checks
  quality:
    name: 🧪 Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: 📥 Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: 📝 Lint code
        run: yarn lint
        
      - name: 🧪 Run tests with coverage
        run: yarn test --coverage
        
      - name: 🔒 Security audit
        run: yarn audit --groups dependencies
        
      - name: 🏗️ Build package
        run: yarn build
        
      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  # 🏷️ Version & Release (on merge to master)
  release:
    name: 🏷️ Release & Publish
    runs-on: ubuntu-latest
    needs: quality
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          
      - name: 📥 Install dependencies
        run: yarn install --frozen-lockfile
        
      # Run semantic-release for automated versioning and publishing
      - name: 🏷️ Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ATHENA_CL_SECRETS_NPM }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          # Configure git with GitHub Actions bot credentials
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          echo "🔍 Analyzing commits for release..."
          
          # Run semantic-release
          npx semantic-release
          
      # Build package AFTER version update
      - name: 🏗️ Build package with updated version
        run: yarn build
          
      # Publish to NPM (after semantic-release creates the package)  
      - name: 📦 Publish to NPM
        if: success()
        env:
          NPM_TOKEN: ${{ secrets.ATHENA_CL_SECRETS_NPM }}
        run: |
          if [ -f "build/package.json" ]; then
            echo "📦 Publishing to NPM..."
            cd build
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish --access public
            echo "✅ Published successfully!"
          else
            echo "⚠️  No release was created by semantic-release"
          fi
